trunk/Dorian/src/fr/dorian/model/Post.java
package fr.dorian.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import fr.dorian.model.Attachment;

import org.apache.commons.lang.builder.ToStringBuilder;
import fr.dorian.model.superclasses.EditableEntity;

@Entity
@Table(name = "post")
@NamedQueries({
	@NamedQuery(name = "Post.findAll",	query = "SELECT p FROM Post p WHERE p.actived = true"),
	@NamedQuery(name = "Post.findById",	query = "SELECT p FROM Post p WHERE p.id = :id"),
	@NamedQuery(name = "Post.findByThread",	query = "SELECT p FROM Post p WHERE p.thread.id = :threadId"),
	@NamedQuery(name = "Post.findByAccount",query = "SELECT p FROM Post p WHERE p.account.id = :accountId"),
	@NamedQuery(name = "Post.countByAccount", query = "SELECT COUNT(p) FROM Post p WHERE p.account.id = :accountId")
})
public class Post extends EditableEntity implements Serializable{

	private static final long serialVersionUID = -7066913043020965006L;

	// PROPERTIES
	///////////////////////////////////////////////////////////////////////////////////////////////
	
	@Column(name = "content", nullable = false)
	private String content;
	
	@Column(name = "actived")
	private boolean actived;
	
	@Column(name = "is_question", nullable=false)
	private boolean question;
	
	@ManyToOne
	@JoinColumn(name = "account_id", nullable = false)
	private Account account;
	
	@ManyToOne
	@JoinColumn(name = "thread_id", nullable = false)
	private Thread thread;
	
	@OneToMany(fetch = FetchType.EAGER)
	@JoinColumn(name = "post_id", referencedColumnName = "id")
	private Set<Attachment> attachments;
	
	// CONSTRUCTORS
	///////////////////////////////////////////////////////////////////////////////////////////////
	
	public Post() {
		super();
		this.setActived(true);
	}

	public Post(Account account, Thread thread, String content) {
		this.setAccount(account);
		this.setThread(thread);
		this.setContent(content);
		this.setActived(true);
	}
	
	// ACCESSORS
	///////////////////////////////////////////////////////////////////////////////////////////////
	
	public String getContent() {return content;}
	public void setContent(String content) {this.content = content;}
	
	public boolean isActived() {return actived;}
	public void setActived(boolean actived) {this.actived = actived;}
	
	public Account getAccount() {return account;}
	public void setAccount(Account owner) {this.account = owner;}
	
	public Thread getThread() {return thread;}
	public void setThread(Thread thread) {this.thread = thread;}
	
	public Set<Attachment> getAttachments() {return attachments;}
	public void setAttachments(Set<Attachment> attachments) {this.attachments = attachments;}

	// HELPER
	///////////////////////////////////////////////////////////////////////////////////////////////

	public void addAttachment(Attachment attachment) {
		if (this.attachments == null)
			this.attachments = new HashSet<Attachment>();
		this.attachments.add(attachment);
	}
	
	public void removeAttachment(Attachment attachment) {
		if (this.attachments != null)
			this.attachments.remove(attachment);
	}

	/**
	 * Check if the current post has been validated by a user.
	 */
	public boolean isValidate() {
		if (this.getThread().getPostValidate() == null)
			return (false);
		else {
			if (this.id == this.getThread().getPostValidate().getId())
				return (true);
		}
		return (false);
	}
	
	//public 
	
	@Override
	public String toString() {
		return new ToStringBuilder(this)
			.append("id", this.id)
			.append("createdAt", this.createdAt)
			.append("content", this.content)
			.append("owner", this.account)
			.append("actived", this.actived)
			.toString();
	}

	public boolean isQuestion() {return question;}
	public void setQuestion(boolean isQuestion) {this.question = isQuestion;}
}

trunk/Dorian/src/fr/dorian/model/Thread.java
package fr.dorian.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;

import fr.dorian.model.superclasses.EditableEntity;

@Entity
@Table(name = "thread")
@NamedQueries({
	@NamedQuery(name = "Thread.findAll", query = "SELECT t FROM Thread t ORDER BY t.id DESC"),
	@NamedQuery(name = "Thread.findById", query = "SELECT t FROM Thread t WHERE t.id = :id"),
	@NamedQuery(name = "Thread.countByAccount", query = "SELECT COUNT(t) FROM Thread t WHERE t.createdBy.id = :accountId"),
	@NamedQuery(name = "Thread.findByAccountId", query = "SELECT t FROM Thread t WHERE t.createdBy.id = :accountId ORDER BY t.id DESC"),
	@NamedQuery(name = "Thread.findPostsByThreadId", query = "SELECT p FROM Post p JOIN p.thread t WHERE t.id = :id ORDER BY p.id ASC"),
	@NamedQuery(name = "Thread.findAllWithReferer",	query = "SELECT t FROM Thread t WHERE LOWER(t.title) LIKE :referer ORDER BY t.id DESC")
//	@NamedQuery(name = "Thread.findRelated", query = "SELECT t FROM Thread t INNER JOIN t.tags tt ON t.id = tt.threaid" + 
//"WHERE tt.tag_id " + 
//"	IN(SELECT itt.tag_id FROM thread_tag itt WHERE itt.thread_id = 1)" + 
//"	AND t.id != 1 GROUP BY t.id"+
//"HAVING COUNT(*) "+
//"LIMIT 3;")
})
	
	/*"INNER JOIN thread_tag tt ON t.id = tt.thread_id" + 
	"WHERE tt.tag_id " + 
	"	IN(SELECT itt.tag_id FROM thread_tag itt WHERE itt.thread_id = 1)" + 
	"	AND t.id != 1 GROUP BY t.id"+
	"HAVING COUNT(*) "+
	"LIMIT 3;"*/
	//@NamedQuery(name = "Thread.findRelated", query = "SELECT t FROM Thread t INNER JOIN () MATCHE")
public class Thread extends EditableEntity implements Serializable {

	private static final long serialVersionUID = 4943712512985988844L;

	// PROPERTIES
	///////////////////////////////////////////////////////////////////////////////////////////////

	@Column(name = "title", nullable = false)
	private String title;
	
	@Column(name = "actived")
	private boolean actived;
	
	// thread closed by owner after best response
	@Column(name = "closed")
	private boolean closed;
	
	@OneToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "post_valid_id", nullable = true)
	private Post postValidate;
	
	@ManyToOne
	@JoinColumn(name = "created_by", nullable = false)
	private Account createdBy;

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "thread_tag",
		joinColumns = {@JoinColumn(name = "thread_id")},
		inverseJoinColumns = {@JoinColumn(name = "tag_id")})
	private Set<Tag> tags;
	
	@OneToMany(fetch = FetchType.EAGER)
	@JoinColumn(name = "thread_id", referencedColumnName = "id")
	private Set<Post> posts;

	/**
	 * Returns the number of posts
	 */
	@Transient
	private Integer postCounter;
	
	// CONSTRUCTORS
	///////////////////////////////////////////////////////////////////////////////////////////////
	
	public Thread() {
		super();
		this.setActived(true);
	}
	
	public Thread(Account account, String title) {
		this.setCreatedBy(account);
		this.setTitle(title);
		this.setActived(true);
	}
	
	// ACCESSORS
	///////////////////////////////////////////////////////////////////////////////////////////////
	
	public String getTitle() {
		return title;
	}

	public boolean isActived() {
		return actived;
	}

	public Account getCreatedBy() {
		return createdBy;
	}

	public boolean isClosed() {
		return closed;
	}

	public void setClosed(boolean closed) {
		this.closed = closed;
	}

	public Set<Tag> getTags() {
		return tags;
	}

	public Set<Post> getPosts() {
		return posts;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public void setActived(boolean actived) {
		this.actived = actived;
	}

	public void setCreatedBy(Account createdBy) {
		this.createdBy = createdBy;
	}

	public void setTags(Set<Tag> tags) {
		this.tags = tags;
	}

	public void setPosts(Set<Post> posts) {
		this.posts = posts;
	}
	
	// HELPER
	///////////////////////////////////////////////////////////////////////////////////////////////
	
	public void addTag(Tag tag) {
		if (this.tags == null)
			this.tags = new HashSet<Tag>();
		this.tags.add(tag);
	}

	public void removeTag(Tag tag) {
		if (this.tags != null)
			this.tags.remove(tag);
	}
	
	public void addPost(Post post) {
		if (this.posts == null)
			this.posts = new HashSet<Post>();
		this.posts.add(post);
	}

	public void removePost(Post post) {
		if (this.posts != null)
			this.posts.remove(post);
	}

	public Integer getPostCounter() {
		if (this.posts != null)
			this.postCounter = this.posts.size();
		return postCounter;
	}
	
	public void setPostCounter(Integer cpt) {
		this.postCounter = cpt;
	}
	
	public Post getPostValidate() {
		return postValidate;
	}
	
	public void setPostValidate(Post postValidate) {
		this.postValidate = postValidate;
	}
	
	@Override
	public String toString() {
		return new ToStringBuilder(this)
			.append("id", this.id)
			.append("title", this.title)
			.append("createdBy", this.createdBy)
			.toString();
	}
}

trunk/Dorian/src/fr/dorian/web/LoginBean.java
package fr.dorian.web;

import java.io.IOException;

public interface LoginBean {
	String doLogin() throws IOException, Exception;

	public String getPassword();
	public String getUsername();
	public boolean isRememberMe();

	public void setPassword(String password);
	public void setUsername(String userId);
	public void setRememberMe(boolean rememberMe);

	public String getEmail();

	boolean isLogged();

	String getDisplayName();

	void setEmail(String email);

	String goToRegistrationPage();
}

trunk/Dorian/src/fr/dorian/web/ThreadBean.java
package fr.dorian.web;

import java.util.List;

import org.primefaces.event.SelectEvent;

import fr.dorian.model.Post;
import fr.dorian.model.Tag;
import fr.dorian.model.Thread;

public interface ThreadBean {

	void getEmpty();

	String createThread();

	String view(Integer threadId);

	String getTitle();

	void setTitle(String title);

	List<Post> findAllPostFromThread();

	Thread getThread();

	String redirectToNewResponse();

	String getContent();

	void setContent(String content);

	String close();

	String addTags();

	List<Tag> getThreadTags();

	List<Thread> getThreadsByAccount(Integer accountId);

	void setThread(Thread thread);

	Integer getId();

	void setId(Integer id);

	List<String> onCompleteTag(String query);

	List<String> getSelectedTagsText();

	void setSelectedTagsText(List<String> selectedTagsText);

	void onSelectTag(SelectEvent event);

	String countByAccount(Integer accountId);

	String validateThread(Integer postId);

	String unvalidateThread(Integer postId);

	String createTutorialFromThread();

	String destroyTutorialByThreadId(Integer threadId);

	String goToAskQuestion();

	String goToThreadList();

	boolean isCanEdit();

	void setCanEdit(boolean canEdit);

}

trunk/Dorian/WebContent/jsp/thread/list.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:sec="http://www.springframework.org/security/tags">

<ui:composition template="../common/template_2c.xhtml">
<ui:param name="param" value="Threads" />
<ui:param name="css" value="../../includes/css/layout_2c.css" />

	<ui:define name="title">
		<h:outputText value="Threads List" styleClass="main-title" />
	</ui:define>
	<ui:define name="body-left">		
		<h:form>
			<p:commandButton id="newQuestion" styleClass="title-button" value="Ask question" action="/jsp/post/askQuestion?faces-redirect=true" />
			<br/>
			<br/>
			<p:dataGrid id="threadsPanel" value="#{threadListBean.allThreads}" var="thread" columns="1"
				rows="20" paginator="true" paginatorPosition="bottom" styleClass="thread-datagrid" paginatorAlwaysVisible="false"
				paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}" >
				
				<p:panel styleClass="thread-datagrid-panel" >
					<h:panelGrid id="threadPanel" columns="2" cellspacing="10">
						<h:panelGrid id="userPanel" columns="1" styleClass="user-panel-grid">
							<p:commandLink id="createdByAvatar" action="#{accountBean.view(thread.createdBy.id)}">
								<p:graphicImage id="avatar" value="#{imageBean.load64(thread.createdBy.id)}" alt="#{thread.createdBy.user.username}"/>
							</p:commandLink>
							<h:commandLink id="threadOwner" value="#{thread.createdBy.user.username}" action="#{accountBean.view(thread.createdBy.id)}" styleClass="username-link"/>
						</h:panelGrid>
						<h:panelGrid id="threadDetailsPanel" columns="1">
							<h:commandLink id="title" value="#{thread.title}" action="#{threadBean.view(thread.id)}" styleClass="thread-title"/>
							<p:dataGrid id="tagsDataGrid" value="#{tagBean.byThread(thread.id)}" var="tag" styleClass="tagsGrid"
								 columns="5" rendered="#{not empty tagBean.byThread(thread.id)}" emptyMessage="No attached tags">
								 <h:commandLink id="tagNameLink" value="#{tag.name}" action="#{tagBean.view(tag.id)}" styleClass="thread-tag-title-link"/>
							</p:dataGrid>
							
							<h:panelGrid id="details" columns="2">
								<h:outputFormat id="modifiedAt" value="#{message['thread.modifiedAt']}" >
									<f:param value="#{thread.modifiedAt}" />
								</h:outputFormat>
								<h:outputText id="count" value="Posts: #{thread.postCounter}"/>
								<h:outputFormat id="createdAt" value="#{message['thread.createdAt']}" >
									<f:param value="#{thread.createdAt}" />
								</h:outputFormat>
								<p:selectBooleanButton id="status" value="#{thread.closed}" onLabel="Closed" onIcon="ui-icon-check" offIcon="ui-icon-close" offLabel="Open" disabled="true" />
							</h:panelGrid>
						</h:panelGrid>
					</h:panelGrid>
				</p:panel>
				
			</p:dataGrid>
		</h:form>
    </ui:define>
    <ui:define name="body-right">
    	<p:outputPanel id="module-filter" layout="block" styleClass="module module-filter">
    		<p:outputPanel id="module-filter-title" layout="block" styleClass="module-filter-title">
    			<h:outputText value="Filter" styleClass="module-title"/>
    		</p:outputPanel>
    	</p:outputPanel>
    	<p:outputPanel id="module-1" layout="block" styleClass="module module-386-280">
    	</p:outputPanel>
    	<p:outputPanel id="module-2" layout="block" styleClass="module module-386-280">
    	</p:outputPanel>
    	<p:outputPanel id="module-3" layout="block" styleClass="module module-386-280">
    	</p:outputPanel>
    </ui:define>
</ui:composition>
</html>

trunk/Dorian/WebContent/jsp/thread/view.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:sec="http://www.springframework.org/security/tags"
	xmlns:p="http://primefaces.org/ui">

<ui:composition template="../common/template.xhtml">
	<ui:param name="param" value="Thread view" />
	<ui:param name="css" value="../../includes/css/layout.css" />
	
	<ui:define name="title">
		<h1>View Thread</h1>
	</ui:define>
	<ui:define name="body">
		<h:form>
			<p:growl id="messages"/>  
			<h:panelGrid id="panelGrid" columns="2" cellpadding="10">
				<h:panelGrid id="mainPanel" columns="1">
					<h:panelGrid id="mpg1" columns="2">
						<p:graphicImage id="gimag1" styleClass="ui-icon ui-icon-comment"/>
						<h:outputText id="threadTitle" value="#{threadBean.thread.title}" styleClass="tutorial-title" />
					</h:panelGrid>
					<h:panelGrid id="pg001" columns="2">
						<p:graphicImage id="avatar2" value="#{imageBean.load32(threadBean.thread.createdBy.id)}" />
						<h:commandLink id="threadOwner" value="#{threadBean.thread.createdBy.user.username}" action="#{accountBean.view(threadBean.thread.createdBy.id)}" styleClass="username-link"/>
					</h:panelGrid>				
					<h:outputFormat id="threadCreatedAt" value="#{message['thread.createdAt']}" >
						<f:param value="#{threadBean.thread.createdAt}" />
					</h:outputFormat>
					<h:outputFormat id="times" value="#{message['thread.modifiedAt']}" >
						<f:param value="#{threadBean.thread.modifiedAt}" />
					</h:outputFormat>
					<h:panelGrid id="tagsPanel" rendered="#{not empty threadBean.threadTags}">
						<p:dataGrid id="tagsDataGrid" value="#{threadBean.threadTags}" var="tag" columns="5" styleClass="tagsGrid">
							 <h:commandLink id="tagNameLink" value="#{tag.name}" action="#{tagBean.view(tag.id)}" styleClass="thread-tag-title-link"/>
						</p:dataGrid>
					</h:panelGrid>
				</h:panelGrid>
				<h:panelGrid id="actions" columns="3">
					<p:commandButton id="close" value="Close" action="#{threadBean.close()}" rendered="#{!threadBean.thread.closed and threadBean.canEdit}"/>
					<p:commandButton id="addTag" value="+tag" onclick="tagDlg.show();" rendered="#{threadBean.canEdit and !threadBean.thread.closed}"/>
					<p:commandButton id="convertToTutorial" value="To tutorial" onclick="confirmation.show()" rendered="#{threadBean.canEdit and !threadBean.thread.closed and threadBean.thread.postValidate != null}" />
					<p:confirmDialog id="confirmDialog" message="Etes-vous sur de vouloir convertir ce thread en tutoriel ?"  
                		header="Initiating destroy process" severity="alert" widgetVar="confirmation">            
        					<p:commandButton id="confirm" value="Yes" update="messages" oncomplete="confirmation.hide()"  
                    			actionListener="#{threadBean.createTutorialFromThread}" />  
        					<p:commandButton id="decline" value="Not" onclick="confirmation.hide()" type="button" />                     
    				</p:confirmDialog>
				</h:panelGrid>
			</h:panelGrid>
			<p:dataList id="table" value="#{threadBean.findAllPostFromThread()}" var="currentPost">
				<p:panel id="de">
					<h:outputText id="content" value="#{currentPost.content}" escape="false"/>
					<br/>
					<p:dataList id="datalist" value="#{attachmentBean.getAttachments(currentPost.id)}" var="attachment">
						<p:panel>
							<p:commandButton id="name" value="#{attachment.fileName}" disabled="#{!attachment.downloadable}" rendered="#{attachment.visible}" ajax="false" icon="ui-icon-arrowthickstop-1-s">
								<p:fileDownload value="#{attachmentBean.download(attachment.id)}" />
							</p:commandButton>
							<p:spacer width="20"/>
							<h:outputText id="descr" value="#{attachment.description}"/>
						</p:panel>
					</p:dataList><br/>
					<h:panelGrid id="pg" columns="4">
						
						<p:panel id="pg0" rendered="#{!currentPost.question and !currentPost.validate and threadBean.canEdit and !threadBean.thread.closed and threadBean.thread.postValidate == null}">
							<h:commandButton id="validate" value="validate" action="#{threadBean.validateThread(currentPost.id)}"/>
						</p:panel>
						<p:panel id="pg1" rendered="#{!currentPost.question and currentPost.validate and threadBean.canEdit and !threadBean.thread.closed and threadBean.thread.postValidate != null}">
							<h:commandButton id="unvalidate" value="unvalidate" action="#{threadBean.unvalidateThread(currentPost.id)}" image="/includes/images/validate.jpg" />
						</p:panel>
						
						<p:panel id="p1" style="border:none;">
							<h:outputFormat id="createdAt" value="#{message['thread.createdAt']}">
								<f:param value="#{currentPost.createdAt}" />
							</h:outputFormat>
							<br/>
							<h:outputFormat id="modifiedAt" value="#{message['thread.modifiedAt']}">
								<f:param value="#{currentPost.createdAt}" />
							</h:outputFormat>
						</p:panel>
						<p:panel id="p2" rendered="#{postBean.canEdit(currentPost) and !threadBean.thread.closed}" style="border:none;">
							<p:panelGrid id="pg2" columns="2">
								<h:commandButton id="deleteCB" value="Delete" action="#{postBean.removePostById(currentPost.id)}"/>
								<h:commandButton id="editPost" value="Edit" action="#{postBean.redirectTo(currentPost)}" />
							</p:panelGrid>
						</p:panel>
						
						<h:panelGrid id="pg3" columns="2">
							<p:graphicImage id="avatar2" value="#{imageBean.load32(currentPost.account.id)}" />
							<p:panel id="p5" style="border:none;">
								<h:commandLink id="username" value="#{currentPost.account.user.username}" action="#{accountBean.view(currentPost.account.id)}" styleClass="username-link"/><br/>
								<h:outputFormat id="reputation" value="#{currentPost.account.accountInfos.reputation}" />
							</p:panel>
						</h:panelGrid>
						
					</h:panelGrid>
				</p:panel>
			</p:dataList>
			<br/>
			<p:commandButton id="addResponse" value="Add response" action="#{threadBean.redirectToNewResponse()}" ajax="false" rendered="#{!threadBean.thread.closed}"/>
		</h:form>
		
		<p:dialog id="tagDialog" header="Add tag" widgetVar="tagDlg" modal="true" minHeight="150">
			<h:form id="addTag">
				<h:panelGrid columns="2" style="margin-bottom:10px">  
	            	<h:outputLabel for="tagName" value="Name:" />
	            	<p:autoComplete id="tagName" completeMethod="#{threadBean.onCompleteTag}" 
	                        multiple="true" forceSelection="true">
	                 	<p:ajax id="onSelectListener" event="itemSelect" listener="#{threadBean.onSelectTag}" ></p:ajax>
	                 </p:autoComplete>
	        	</h:panelGrid>
            	<p:commandButton id="cancel" value="Cancel" onclick="tagDlg.hide();"/>
            	<p:commandButton id="createButton" value="Submit" action="#{threadBean.addTags}"/>
			</h:form>
   		</p:dialog>  
	</ui:define>
	</ui:composition>
</html>